"""Markdown reporter — file output suitable for client deliverables.

The markdown report is what gets attached to "here's your AWS cost audit"
emails. It's designed to render well on GitHub, in VS Code's markdown
preview, and after pandoc-conversion to PDF.

Structure: executive summary at the top (savings, severity breakdown),
then findings as expandable sections with full fix suggestions.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from cost_optimizer.core import Severity
from cost_optimizer.reporters.base import Reporter

if TYPE_CHECKING:
    from cost_optimizer.core.orchestrator import ScanResult


class MarkdownReporter(Reporter):
    """Render findings as a Markdown document."""

    def render(self, result: ScanResult) -> str:
        sections = [
            self._header(result),
            self._summary(result),
            self._findings(result),
            self._failures(result),
            self._footer(),
        ]
        return "\n\n".join(s for s in sections if s)

    def _header(self, result: ScanResult) -> str:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        return (
            f"# AWS Cost Audit Report\n\n"
            f"**Account:** `{result.account_id or 'unknown'}`  \n"
            f"**Region:** `{result.region}`  \n"
            f"**Scan date:** {timestamp}  \n"
            f"**Scan duration:** {result.duration_seconds:.1f}s"
        )

    def _summary(self, result: ScanResult) -> str:
        if not result.findings:
            return "## Summary\n\nNo cost waste detected. Account looks clean."

        by_severity: dict[Severity, int] = {Severity.HIGH: 0, Severity.MEDIUM: 0, Severity.LOW: 0}
        savings_by_severity: dict[Severity, float] = {
            Severity.HIGH: 0.0,
            Severity.MEDIUM: 0.0,
            Severity.LOW: 0.0,
        }
        for f in result.findings:
            by_severity[f.severity] += 1
            savings_by_severity[f.severity] += f.monthly_savings_usd

        rows = [
            "| Severity | Findings | Estimated savings/mo |",
            "|----------|---------:|---------------------:|",
        ]
        for sev in (Severity.HIGH, Severity.MEDIUM, Severity.LOW):
            rows.append(f"| {sev.value} | {by_severity[sev]} | ${savings_by_severity[sev]:,.0f} |")
        rows.append(
            f"| **Total** | **{len(result.findings)}** | "
            f"**${result.total_monthly_savings_usd:,.0f}** |"
        )

        table = "\n".join(rows)
        return f"## Summary\n\n{table}"

    def _findings(self, result: ScanResult) -> str:
        if not result.findings:
            return ""

        parts = ["## Findings"]
        for i, finding in enumerate(result.findings, start=1):
            savings = (
                f"${finding.monthly_savings_usd:,.0f}/mo"
                if finding.monthly_savings_usd > 0
                else "savings unknown"
            )
            parts.append(
                f"### {i}. {finding.title}\n\n"
                f"- **Severity:** {finding.severity.value}\n"
                f"- **Estimated savings:** {savings}\n"
                f"- **Resource:** `{finding.resource_id}` ({finding.resource_type})\n"
                f"- **Region:** `{finding.region}`\n"
                f"- **Analyzer:** `{finding.analyzer}`\n\n"
                f"**Details:** {finding.description}\n\n"
                f"**Recommended fix:** {finding.fix_suggestion}"
            )
        return "\n\n".join(parts)

    def _failures(self, result: ScanResult) -> str:
        if not result.failures:
            return ""

        rows = ["| Analyzer | Error type | Message |", "|----------|-----------|---------|"]
        for fail in result.failures:
            # Markdown table rows can't contain literal pipes — escape them.
            safe_msg = fail.message.replace("|", "\\|")
            rows.append(f"| `{fail.analyzer}` | {fail.error_type} | {safe_msg} |")

        return "## Analyzer failures\n\n" + "\n".join(rows)

    def _footer(self) -> str:
        return (
            "---\n\n"
            "_Generated by [aws-cost-audit](https://github.com/) — "
            "open source AWS cost optimization tool._"
        )
